23:13:33 - 来自: main.py:1711 - <module>                        | 调用函数            | __main__.__init__                        | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:34 -     来自: main.py:1525 - __init__                        | 调用函数            | __main__.__init__                        | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:34 -     来自: main.py:1525 - __init__                        | 函数返回            | __main__.__init__                        | 返回值: None
23:13:34 -     来自: main.py:1526 - __init__                        | 调用函数            | __main__.init_info                       | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:34 -     来自: main.py:1526 - __init__                        | 函数返回            | __main__.init_info                       | 返回值: None
23:13:34 - 来自: main.py:1711 - <module>                        | 函数返回            | __main__.__init__                        | 返回值: None
23:13:37 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.auto_game                       | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': 'False'}
23:13:37 - 来自: 未知调用者                                          | 调用函数            | __main__.run                             | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:37 -     来自: main.py:259 - run                              | 调用函数            | __main__.init_datas                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:37 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.auto_game                       | 返回值: None
23:13:37 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:37 -     来自: main.py:1627 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:37 -     来自: main.py:1627 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
23:13:37 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.init_interface                  | 返回值: None
23:13:37 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.write_threshold                 | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:37 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.write_threshold                 | 返回值: None
23:13:37 -     来自: main.py:259 - run                              | 函数异常            | __main__.init_datas                      | 异常类型: KeyError | 异常信息: 'state' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 308, in init_datas
    self.statement = data["state"]
KeyError: 'state'

23:13:37 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:37 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:37 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:37 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:37 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:37 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:37 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:37 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:39 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:39 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:39 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:39 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:39 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:39 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:39 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:39 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:41 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:41 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:41 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:41 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:41 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:41 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:41 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:41 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:43 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:43 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:43 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:43 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:43 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:43 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:43 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:43 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:45 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:45 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:45 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:45 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:45 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:45 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:45 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:45 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:47 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:47 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:47 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:47 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:47 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:47 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:47 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:47 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:48 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.stop                            | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': 'False'}
23:13:48 -     来自: main.py:1573 - stop                            | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:48 -         来自: main.py:1627 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:48 -         来自: main.py:1627 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
23:13:48 -     来自: main.py:1573 - stop                            | 函数返回            | __main__.init_interface                  | 返回值: None
23:13:48 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.stop                            | 返回值: None
23:13:51 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.auto_game                       | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': 'False'}
23:13:51 - 来自: 未知调用者                                          | 调用函数            | __main__.run                             | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:51 -     来自: main.py:259 - run                              | 调用函数            | __main__.init_datas                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:51 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.auto_game                       | 返回值: None
23:13:51 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:51 -     来自: main.py:1627 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:51 -     来自: main.py:1627 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
23:13:51 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.init_interface                  | 返回值: None
23:13:51 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.write_threshold                 | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:51 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.write_threshold                 | 返回值: None
23:13:51 -     来自: main.py:259 - run                              | 函数异常            | __main__.init_datas                      | 异常类型: KeyError | 异常信息: 'state' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 308, in init_datas
    self.statement = data["state"]
KeyError: 'state'

23:13:51 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:51 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:51 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:51 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:51 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:51 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:51 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:51 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:53 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:53 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:53 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:53 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:53 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:53 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:53 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:53 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:55 -     来自: main.py:285 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:55 -         来自: main.py:672 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:55 -         来自: main.py:672 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: AttributeError | 异常信息: 'Worker' object has no attribute 'model' | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 352, in find_my_cards
    my_cards_real = self.cards_info(img, self.MyCardsPos, mark="m")
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 324, in cards_info
    results = self.model(crop_img)
AttributeError: 'Worker' object has no attribute 'model'

23:13:55 -     来自: main.py:285 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 676, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

23:13:55 -     来自: main.py:287 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x0000020809FE3280>'}
23:13:55 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '出牌前阶段'}
23:13:55 -     来自: main.py:287 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "c:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/User/Desktop/douzero项目汇总/测试用/5.8源码cursor版/main.py", line 910, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

23:13:55 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
23:13:56 - 来自: main.py:1713 - <module>                        | 调用函数            | __main__.stop                            | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': 'False'}
23:13:56 -     来自: main.py:1573 - stop                            | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>', 'result': '1'}
23:13:56 -         来自: main.py:1627 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000208085FCCA0>'}
23:13:56 -         来自: main.py:1627 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
23:13:56 -     来自: main.py:1573 - stop                            | 函数返回            | __main__.init_interface                  | 返回值: None
23:13:56 - 来自: main.py:1713 - <module>                        | 函数返回            | __main__.stop                            | 返回值: None
